#!/bin/bash

# Copyright (C) 2026 Pirx Developers - https://pirx.dev/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
  cat <<EOF
Usage: $(basename "$0") -z DNS_ZONE -n NAME

Options:
  -z <zone> - name of DNS zone to edit
  -n <record> - name of DNS record to set/update/remove
  -l <path> - path to log file, leave empty to disable logging
  -h - show this help
EOF
  exit 0
}

log() {
  if [ -z "${log_file}" ]; then
    echo "$@"
  else
    echo "$(date +"%Y-%m-%d %H:%M:%S") $@" | tee -a "${log_file}"
  fi
}

script_dir="$(realpath "${0}")"
script_dir="$(dirname "${script_dir}")"

if test -f "${script_dir}/shared"; then
  . "${script_dir}/shared"
else
  log "Shared code file not found or not readable"
  exit 1
fi

while getopts ":z:n:l:h" option; do
  case "${option}" in
    z) zone="${OPTARG}" ;;
    n) name="${OPTARG}" ;;
    l) log_file="${OPTARG}" ;;
    h) usage ;;
    :)
      log "Error: option -${OPTARG} requires an argument"
      exit 1
      ;;
    \?)
      log "Error: invalid option -${OPTARG}"
      exit 1
      ;;
  esac
done

if [ -z "${ip_check_url}" ]; then
  log "Error: IP check URL must be specified in ${script_dir}/config"
  exit 1
fi

if [ -z "${zone}" ]; then
  log "Error: DNS zone is required"
  exit 1
fi

if [ -z "${name}" ]; then
  log "Error: DNS record name is required"
  exit 1
fi

api_data=$(cf_api GET "zones?name=${zone}") || bail_out "${api_data}"
if [ $(echo "${api_data}" | jq -r '.result_info["count"]') -eq 0 ]; then
  log "DNS zone ${zone} not found"
  exit 1
fi

zone_id=$(echo "${api_data}" | jq -r '.result[0].id')
if [ -z "${zone_id}" ]; then
  log "Error getting DNS zone id"
  exit 1
fi

api_data=$(cf_api GET "zones/${zone_id}/dns_records?type=A&name=${name}.${zone}") || bail_out "${api_data}"
if [ $(echo "${api_data}" | jq -r '.result_info["count"]') -eq 0 ]; then
  cf_ip="<none>"
else
  cf_ip=$(echo "${api_data}" | jq -r '.result[0].content')
fi

current_ip=$(curl -s "${ip_check_url}" 2>/dev/null)
if [ $? -ne 0 ]; then
  log "Error querying ${ip_check_url}"
  exit 1
fi

if ! [[ "${current_ip}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
  log "Web check returned invalid IP"
  exit 1
fi

if [ "${current_ip}" != "${cf_ip}" ]; then
  output=$("${script_dir}/cf-dns" \
    -a set \
    -z ${zone} \
    -n ${name} \
    -v ${current_ip} \
    -t A \
    -l 60 \
    -p false \
    2>&1)
  if [ $? -eq 0 ]; then
    log "IP updated from ${cf_ip} to ${current_ip}"
  else
    log "Error updating IP from ${cf_ip} to ${current_ip}"
    log "${output}"
    exit 1
  fi
fi

exit 0
